/** The same direct-registration example for both adapters. Photos use a stable Picsum seed. */
export const RICH_COMPONENTS_EXAMPLE = [
  '## Code, images and tables',
  '```json',
  '{"message":"Copy keeps the original source","count":3}',
  '```',
  '```mermaid',
  'graph LR; Markdown-->Components; Components-->React; Components-->Vue',
  '```',
  '',
  'Click the image below to open its preview.',
  '',
  '![Sample photo from Picsum](https://picsum.photos/seed/ai-markdown-preview/200/300)',
  '',
  '| Component | Registration |',
  '| :-- | :-- |',
  '| Code + Mermaid | `pre` |',
  '| Image preview | `img` |',
  '| Table export | `table` |',
].join('\n');
